### ISSUE TITLE
Wrong code in obsc text?

### ISSUE THREAD

**Issue by sam-falvo** [suhr/obsc#2]
In https://suhr.github.io/obsc/ , you have written:  `drop dup (^2) + (^2) - abs` as a solution for solving the y^2 + x^2 - |y| equation.  It seems from your Factor example that the input stack effect is (x y z).  If this is true, and the infix operator pattern works as described previously in the article, then the aforementioned obsc must be wrong, as illustrated in the following table:

| Operation | Stack |
|:--:|:---|
| |`x y z`|
|`drop`|`x y`|
|`dup`|`x y y`|
|`(^2) + (^2)`|`x 2y^2`|
|`-`|`x-2y^2`|
|`abs`|`\|x-2y^2\|`|

If it's intended that the order of stacked inputs differs from the Factor code, then it should be made clear in the article that this is the case.  Otherwise, it'll lead to confusion.

**Comment by suhr** [comment]
Minus is infix too. So `(^2) + (^2) - abs` is `((^2);(^2) +);abs -`. `(^2);(^2) +` is a function that takes two values and returns one, and `abs` is a function that takes and return only one value. So `((^2);(^2) +);abs` takes three values and returns two.

Graphically,

```
 +       +       +
 |       |       |
(^2)    (^2)     |
 |       |       |
 +->(+)<-+     (abs)
     |           |
     +--->(-)<---+
           |
           v
```

**Comment by sam-falvo** [comment]
Ahhh, I did not think to nest expressions that way.  That makes much more sense.  Thank you!
